spring:
  application:
    name: user-management

  datasource:
    url: jdbc:oracle:thin:@//172.16.15.18:1521/FREEPDB1
    username: app_user
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      operationsSorter: method
      tagsSorter: alpha

server:
  port: 8080
